SELECT dia_semana, concelho,sum(unidades)
FROM vendas
WHERE ano >= EXTRACT(YEAR FROM TIMESTAMP '2000-01-01')
AND ano <= EXTRACT(YEAR FROM TIMESTAMP '2000-03-03')
AND mes >= EXTRACT(MONTH FROM TIMESTAMP '2000-01-01')
AND mes <= EXTRACT(MONTH FROM TIMESTAMP '2000-03-03')
AND dia_mes >= EXTRACT(DAY FROM TIMESTAMP '2000-01-01')
AND dia_mes <= EXTRACT(DAY FROM TIMESTAMP '2000-03-03')
GROUP BY ROLLUP (dia_semana, concelho, unidades)
ORDER BY (dia_semana,concelho,unidades);
